language: ruby
rvm:
 - 2.5.0

before_script:
  - psql -c "CREATE USER Blog WITH PASSWORD 'password';" -U postgres

script:
 - bundle exec rubocop
 - bundle exec rake db:create:all
 - bundle exec rake db:migrate
 - bundle exec rake spec
