language: ruby
rvm:
 - 2.5.0

services:
  - postgresql

env:
  - RAILS_ENV=test

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
 - bundle exec rubocop
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
